# Generated by Django 5.0.3 on 2025-03-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code_prefix',
            field=models.CharField(default=54, max_length=2, unique=True, verbose_name='Prefixo do Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
