# Generated by Django 5.0.2 on 2025-05-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Quantidade em Estoque'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'code'], name='store_produ_name_fede9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='store_produ_stock_q_9290bd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'stock_quantity'], name='store_produ_categor_52a50a_idx'),
        ),
    ]
