# Generated by Django 5.0.2 on 2025-05-03 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_code_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='sale',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10),
        ),
        migrations.CreateModel(
            name='StockMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
