# Generated by Django 5.0.2 on 2025-05-03 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement_items', to='store.product'),
        ),
    ]
