# Generated by Django 5.0.3 on 2025-04-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_category_code_prefix_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Vendas')),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro Total')),
                ('total_items', models.PositiveIntegerField(verbose_name='Total de Itens Vendidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Relatório de Vendas',
                'verbose_name_plural': 'Relatórios de Vendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopProductsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Relatório de Produtos Mais Vendidos',
                'verbose_name_plural': 'Relatórios de Produtos Mais Vendidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopProductsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(verbose_name='Quantidade Vendida')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Receita Total')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Produto')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.topproductsreport')),
            ],
            options={
                'verbose_name': 'Item do Relatório de Produtos',
                'verbose_name_plural': 'Itens do Relatório de Produtos',
                'ordering': ['-quantity_sold'],
            },
        ),
    ]
